### ISSUE TITLE
Support for Virtual Private Servers

### ISSUE THREAD

**Issue by petericebear** [verschoof/transip-api#7]
Hello,

Are you going to support Virtual Private Servers in the future?

With kind regards,
Peter

**Comment by petericebear** [comment]
I created a pull requests, if you like it, maybe you can add it to the master?

**Comment by verschoof** [comment]
Hi Peter,

Thanks for your PR! It's merged and I have created a new tag.
I didn't test your code but it looked good! :+1: 

New tag: `v1.2.0`
